[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
{type = 'Joker', val = G.GAME.joker_rate},
''' 
position = "after"
payload = ''' 
{type = 'xiferp_Element', val = G.GAME.element_rate or 2},
''' 
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
edition_rate = 1,
joker_rate = 20,
tarot_rate = 4,
planet_rate = 4, 
spectral_rate = 0,
''' 
position = "after"
payload = ''' 
element_rate = 2,
''' 
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''if obj and obj.set_badges and type(obj.set_badges) == 'function' then'''
position = "before"
payload = '''
if card and card.ability then
    if card:has_attribute('food') then
        badges[#badges+1] = create_badge('Food Joker', HEX('a06a16'), HEX('ffffff'), 1)
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''if obj and obj.set_badges and type(obj.set_badges) == 'function' then'''
position = "before"
payload = '''
if card and card.ability then
    if card:has_attribute('drink') then
        badges[#badges+1] = create_badge('Drink Joker', HEX('804000'), HEX('ffffff'), 1)
    end
end
'''
match_indent = true